=== LorenzoMarchisio05/XML/ES05/file.dtd
<!ELEMENT root (sessione*) >
<!ELEMENT sessione (id, account, video+) >
<!ELEMENT id (#PCDATA) >
<!ELEMENT video (commento*) >
<!ATTLIST video 
            nome CDATA #REQUIRED 
            serie CDATA #IMPLIED >
<!ELEMENT commento (nome-utente, messaggio) >
<!ELEMENT nome-utente (#PCDATA) >
<!ELEMENT messaggio (#PCDATA) >
<!ELEMENT account (sotto-account*) >
<!ATTLIST account 
            nome CDATA #REQUIRED 
            email CDATA #REQUIRED 
            tipo (normale|premium|vip) #REQUIRED >
<!ELEMENT sotto-account EMPTY >
<!ATTLIST sotto-account 
            nome CDATA #REQUIRED >

=== LorenzoMarchisio05/XML/ES05/file.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE root SYSTEM "file.dtd">
<root>
    <sessione>
        <id>ID</id>
        <account nome="nome" email="mail@gmail" tipo="normale">
            <sotto-account nome="nomesotto account" />
            <sotto-account nome="nomesotto account" />
        </account>
        <video nome="video 1">
            <commento>
                <nome-utente>nome</nome-utente>
                <messaggio>messaggio commento</messaggio>
            </commento>
        </video>
    </sessione>
    <sessione>
        <id>ID</id>
        <account nome="nome" email="mail@gmail" tipo="premium">
        </account>
        <video nome="video 1">
            <commento>
                <nome-utente>nome</nome-utente>
                <messaggio>messaggio commento</messaggio>
            </commento>
        </video>
        <video nome="video 2">
            <commento>
                <nome-utente>commento 2</nome-utente>
                <messaggio>messaggio commento</messaggio>
            </commento>
        </video>
    </sessione>
</root>
