=== LorenzoMarchisio05/XML/ES02/file.dtd
<!ELEMENT verbali (verbale)* >
<!ELEMENT verbale (studente, esame*) >
<!ATTLIST verbale 
            id CDATA #IMPLIED >
<!ELEMENT studente (nome+, cognome) >
<!ATTLIST studente 
            cdl CDATA #REQUIRED
            matr CDATA #REQUIRED >
<!ELEMENT nome (#PCDATA) >
<!ELEMENT cognome (#PCDATA) >
<!ELEMENT esame (materia, docente, voto, lode?, data) >
<!ELEMENT materia (#PCDATA) >
<!ELEMENT docente (#PCDATA) >
<!ELEMENT voto (#PCDATA) >
<!ELEMENT lode (#PCDATA) >
<!ELEMENT data (#PCDATA) >

=== LorenzoMarchisio05/XML/ES02/file.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE verbali SYSTEM "file.dtd">
<verbali>
    <verbale>
        <studente cdl="007" matr="001234">
            <nome>nome</nome> <nome>nome</nome>
            <cognome>cognome</cognome>
        </studente>
        <esame>
            <materia>Gastronomia</materia> <docente>Vissani</docente>
            <voto>30</voto> <lode>SI</lode> <data>12/04/2000</data>
        </esame>
    </verbale>
</verbali>
